services:
  finance-app:
    image: 10.70.70.70:3000/rayns-domain/livefinanceapp:latest
    container_name: finance-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - /var/lib/docker-stacks/livefinanceapp/appdata/.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
